# Generated by Django 5.2.6 on 2025-09-15 20:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('hp', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('attack', models.PositiveIntegerField()),
                ('defense', models.PositiveIntegerField()),
                ('speed', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('attack_modifier', models.FloatField(default=1.0)),
                ('defense_modifier', models.FloatField(default=1.0)),
                ('speed_modifier', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_cron', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SCHEDULED', 'SCHEDULED'), ('RUNNING', 'RUNNING'), ('FINISHED', 'FINISHED'), ('FAILED', 'FAILED')], default='PENDING', max_length=12)),
                ('log', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pokemon_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_a', to='battles.pokemon')),
                ('pokemon_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_b', to='battles.pokemon')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wins', to='battles.pokemon')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='battles.scenario')),
            ],
        ),
    ]
