# Generated by Django 5.2.6 on 2025-09-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='battle',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='pokemon',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='scenario',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='battle',
            name='state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
