# Generated by Django 5.2.6 on 2025-09-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0002_alter_battle_options_alter_pokemon_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('SCHEDULED', 'Programado'), ('RUNNING', 'En ejecución'), ('FINISHED', 'Finalizado'), ('FAILED', 'Fallido')], default='PENDING', max_length=12),
        ),
    ]
