# Generated by Django 5.2.6 on 2025-09-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0003_battle_name_alter_battle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='run_count_cron',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battle',
            name='run_count_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
